/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreeIndexRouteImport } from './routes/tree/index'
import { Route as AqiIndexRouteImport } from './routes/aqi/index'
import { Route as ActivityIndexRouteImport } from './routes/activity/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AqiCityRouteImport } from './routes/aqi/$city'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreeIndexRoute = TreeIndexRouteImport.update({
  id: '/tree/',
  path: '/tree/',
  getParentRoute: () => rootRouteImport,
} as any)
const AqiIndexRoute = AqiIndexRouteImport.update({
  id: '/aqi/',
  path: '/aqi/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityIndexRoute = ActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AqiCityRoute = AqiCityRouteImport.update({
  id: '/aqi/$city',
  path: '/aqi/$city',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/products': typeof ProductsRoute
  '/aqi/$city': typeof AqiCityRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/activity': typeof ActivityIndexRoute
  '/aqi': typeof AqiIndexRoute
  '/tree': typeof TreeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/products': typeof ProductsRoute
  '/aqi/$city': typeof AqiCityRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/activity': typeof ActivityIndexRoute
  '/aqi': typeof AqiIndexRoute
  '/tree': typeof TreeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/products': typeof ProductsRoute
  '/aqi/$city': typeof AqiCityRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/activity/': typeof ActivityIndexRoute
  '/aqi/': typeof AqiIndexRoute
  '/tree/': typeof TreeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/products'
    | '/aqi/$city'
    | '/auth/login'
    | '/auth/register'
    | '/activity'
    | '/aqi'
    | '/tree'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/products'
    | '/aqi/$city'
    | '/auth/login'
    | '/auth/register'
    | '/activity'
    | '/aqi'
    | '/tree'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/products'
    | '/aqi/$city'
    | '/auth/login'
    | '/auth/register'
    | '/activity/'
    | '/aqi/'
    | '/tree/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  ProductsRoute: typeof ProductsRoute
  AqiCityRoute: typeof AqiCityRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ActivityIndexRoute: typeof ActivityIndexRoute
  AqiIndexRoute: typeof AqiIndexRoute
  TreeIndexRoute: typeof TreeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree/': {
      id: '/tree/'
      path: '/tree'
      fullPath: '/tree'
      preLoaderRoute: typeof TreeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aqi/': {
      id: '/aqi/'
      path: '/aqi'
      fullPath: '/aqi'
      preLoaderRoute: typeof AqiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/': {
      id: '/activity/'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aqi/$city': {
      id: '/aqi/$city'
      path: '/aqi/$city'
      fullPath: '/aqi/$city'
      preLoaderRoute: typeof AqiCityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  ProductsRoute: ProductsRoute,
  AqiCityRoute: AqiCityRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ActivityIndexRoute: ActivityIndexRoute,
  AqiIndexRoute: AqiIndexRoute,
  TreeIndexRoute: TreeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
