/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreeIndexRouteImport } from './routes/tree/index'
import { Route as AqiIndexRouteImport } from './routes/aqi/index'
import { Route as ActivityIndexRouteImport } from './routes/activity/index'
import { Route as AqiCityRouteImport } from './routes/aqi/$city'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreeIndexRoute = TreeIndexRouteImport.update({
  id: '/tree/',
  path: '/tree/',
  getParentRoute: () => rootRouteImport,
} as any)
const AqiIndexRoute = AqiIndexRouteImport.update({
  id: '/aqi/',
  path: '/aqi/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityIndexRoute = ActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => rootRouteImport,
} as any)
const AqiCityRoute = AqiCityRouteImport.update({
  id: '/aqi/$city',
  path: '/aqi/$city',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aqi/$city': typeof AqiCityRoute
  '/activity': typeof ActivityIndexRoute
  '/aqi': typeof AqiIndexRoute
  '/tree': typeof TreeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aqi/$city': typeof AqiCityRoute
  '/activity': typeof ActivityIndexRoute
  '/aqi': typeof AqiIndexRoute
  '/tree': typeof TreeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aqi/$city': typeof AqiCityRoute
  '/activity/': typeof ActivityIndexRoute
  '/aqi/': typeof AqiIndexRoute
  '/tree/': typeof TreeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/aqi/$city' | '/activity' | '/aqi' | '/tree'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/aqi/$city' | '/activity' | '/aqi' | '/tree'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/aqi/$city'
    | '/activity/'
    | '/aqi/'
    | '/tree/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AqiCityRoute: typeof AqiCityRoute
  ActivityIndexRoute: typeof ActivityIndexRoute
  AqiIndexRoute: typeof AqiIndexRoute
  TreeIndexRoute: typeof TreeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree/': {
      id: '/tree/'
      path: '/tree'
      fullPath: '/tree'
      preLoaderRoute: typeof TreeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aqi/': {
      id: '/aqi/'
      path: '/aqi'
      fullPath: '/aqi'
      preLoaderRoute: typeof AqiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/': {
      id: '/activity/'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aqi/$city': {
      id: '/aqi/$city'
      path: '/aqi/$city'
      fullPath: '/aqi/$city'
      preLoaderRoute: typeof AqiCityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AqiCityRoute: AqiCityRoute,
  ActivityIndexRoute: ActivityIndexRoute,
  AqiIndexRoute: AqiIndexRoute,
  TreeIndexRoute: TreeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
